# Generated by Django 2.0.1 on 2018-02-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_stock_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='mediaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageFil', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
