# Generated by Django 2.0.1 on 2018-02-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_mediaimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mediaImage',
        ),
    ]
