# Generated by Django 2.0.1 on 2018-02-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_delete_mediaimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='ticker',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='close',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='opening',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='volume',
        ),
    ]
